# ---------------------------------
#   Tema
# ---------------------------------
remote_theme: cotes2020/jekyll-theme-chirpy

# ---------------------------------
#   Plugins
# ---------------------------------
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-include-cache

# ---------------------------------
#   Datos básicos
# ---------------------------------
title: Daniel Fulla Pairo
tagline: LeetCode Blog & Projects    # traducido al inglés
description: >
  This is where I will be uploading my LeetCode solutions with explanations.
  I will also be sharing some personal & team projects for feedback.
email: daniel_fulla@icloud.com

url: ""          # p. ej. https://dpairo.github.io cuando publiques
baseurl: ""      # déjalo vacío si publicas en la raíz

lang: en-US      # cambia a en-US si todo el contenido va en inglés
timezone: Europe/Madrid

github_username: dpairo
instagram_username: daniifulla

# ---------------------------------
#   Foto de perfil
# ---------------------------------
avatar: /assets/Img/profilePick.jpg

# ---------------------------------
#   Paginación
# ---------------------------------
paginate: 10
paginate_path: "/page:num/"

# ---------------------------------
#   Eliminar “Actualizado recientemente”
# ---------------------------------
recent_posts:
  enable: false