# ---------------------------------
#   Datos básicos
# ---------------------------------
title: Daniel Fulla Pairo
tagline: Leetcode & projects blog
description: >
  This is where I will be uploading my LeetCode solutions with explanations.
  I will also be sharing some personal & team projects for feedback.
email: daniel_fulla@icloud.com

url: ""          # p. ej. https://dpairo.github.io cuando publiques
baseurl: ""      # déjalo vacío si publicas en la raíz

lang: es-ES
timezone: Europe/Madrid

github_username: dpairo
instagram_username: daniifulla

# ---------------------------------
#   Tema
# ---------------------------------
theme: jekyll-theme-chirpy       # ahora es una gem, no un remote‑theme

# ---------------------------------
#   Foto de perfil
# ---------------------------------
avatar: /assets/Img/profilePick.jpg

# ---------------------------------
#   Paginación
# ---------------------------------
paginate: 10                     # nº de posts por página de inicio
paginate_path: "/page:num/"

# ---------------------------------
#   Plugins adicionales
# ---------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll/tagging        # ← con slash
  - jekyll-include-cache

# ---------------------------------
#   cargarse el recientemente
# ---------------------------------
recent_post:
  enable: false
